### ISSUE TITLE
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

### ISSUE THREAD

**Issue by Kaioken3000** [flet-dev/serious-python#114]
I don't know why it not run, when i remove the code, then it run ok, so it must be at english_ipa, but i dont know how to fix it, please help me!!!

error:
Running Python program synchronously...Traceback (most recent call last):
  File "C:\Users\Nam\AppData\Roaming\com.example\demospeech\flet\assets\main.py", line 5, in <module>
    from pydantic import BaseModel, Field
  File "C:\Users\Nam\AppData\Roaming\com.example\demospeech\flet\assets\__pypackages__\pydantic\__init__.py", line 411, in __getattr__
    module = import_module(module_name, package=package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python312-dist\Lib\importlib\__init__.py", line 90, in import_module
  File "C:\Users\Nam\AppData\Roaming\com.example\demospeech\flet\assets\__pypackages__\pydantic\main.py", line 28, in <module>
    import pydantic_core
  File "C:\Users\Nam\AppData\Roaming\com.example\demospeech\flet\assets\__pypackages__\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ModuleNotFoundError: No module named 'pydantic_core._pydantic_core'

python code:
from english_ipa.cambridge import CambridgeDictScraper
scraper = CambridgeDictScraper()
text = scraper.get_ipa_in_dict("demo")
print(text)

flutter code:
SeriousPython.run(
      "assets/demofastapi.zip",
      sync: true,
    );

**Comment by aalapd** [comment]
Also getting this issue. @Kaioken3000 did you ever find a solution?

**Comment by aalapd** [comment]
Serious Python only supports "pure" python packages. pydantic_core will not work because IIRC it is written in Rust. You'll have to use an older version of pydantic that does not require pydantic_core which I think is 1.8.2.

**Comment by FeodorFitsner** [comment]
@aalapd That's not true. Serious Python supports both pure and binary packages for all platforms, including iOS and Android.

**Comment by aalapd** [comment]
@FeodorFitsner  It's very much true. It literally says so in the [documentation](https://pub.dev/packages/serious_python). Please see the section on Supported Python packages.

**Comment by kaixin1106** [comment]
Has anyone solved it?

I found that binary packages are not supported on Windows, but are OK on macOS

GPT tells me this. And the results are pretty good.

<img width="1141" height="552" alt="Image" src="https://github.com/user-attachments/assets/0025e048-08b6-4c4f-a927-fea65457709f" />

**Comment by ndonkoHenri** [comment]
Please retry on 4.5.1+ with the current flow. If `pydantic` still fails to import, open a fresh issue with the `package` command's `--verbose` output — that will show whether the wheel resolved.
