### ISSUE TITLE
When debugging the app using Android Studio temporary folder is not erased properly

### ISSUE THREAD

**Issue by ismael-benito** [flet-dev/serious-python#47]
Hi there, 

when trying to run a minimal example (counter) with the following environment: 

```
Debian GNU/Linux 12 (bookworm)
Android Studio Hedgehog | 2023.1.1
Flutter 3.16.4
```

I constantly have to manually remove the temporal folder created for the python code in both the Linux and Android environments, this error arises: 

```
Debug service listening on ws://127.0.0.1:45185/uwcCXYfS2XI=/ws
Syncing files to device Linux...
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Deletion failed, path = '/tmp/example-1.0.0-1/.' (OS Error: Argumento inválido, errno = 22)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185:7)
<asynchronous suspension>
#2      extractAssetOrFile (package:serious_python_platform_interface/src/utils.dart:29:7)
<asynchronous suspension>
#3      SeriousPython.run (package:serious_python/serious_python.dart:45:17)
<asynchronous suspension>
```

In the case of Android, the `rm` command can be a little bit tricky: 

```
adb exec-out run-as com.youcompany.example rmdir /data/user/0/com.yourcompany.example/app_flutter/example-1.0.0-1/
```

After removing the folder, and hot loading it again, it works. 

Am I missing something? 

Cheers,

**Comment by ndonkoHenri** [comment]
`extractAssetOrFile` — and the entire first-launch zip-extraction path that trace comes from — no longer exists. Since 4.0.0 your Python app ships **unpacked inside the app bundle** on Linux/macOS/Windows/iOS, so nothing is written to a temp dir at all; on Android it's a stored `app.zip` unpacked once to app-support under a version key. 4.3.4 additionally fixed stale code surviving a same-version reinstall under `flet debug android` by folding the install timestamp into that key.

So there's nothing left to `rm` between runs. Closing as obsolete against 4.5.1+ — please open a new issue if you see anything similar on current versions.
