### ISSUE TITLE
Local socket connection error

### ISSUE THREAD

**Issue by C69Xg3sg9PAvYK** [flet-dev/serious-python#72]
Hello, 

I have previously created an app without any issue. However when I tried to do the same today, I am getting this error.

Traceback (most recent call last):
  File "<string>", line 40, in <module>
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/var/folders/2v/_cn0vsc92ss3fvq34ndm1nk00000gn/T/serious_python_tempz9FFEv/main.py", line 424, in <module>
  File "/var/folders/2v/_cn0vsc92ss3fvq34ndm1nk00000gn/T/serious_python_tempz9FFEv/__pypackages__/flet_runtime/app.py", line 91, in app
  File "/var/folders/2v/_cn0vsc92ss3fvq34ndm1nk00000gn/T/serious_python_tempz9FFEv/__pypackages__/flet_runtime/app.py", line 128, in __app_sync
  File "/var/folders/2v/_cn0vsc92ss3fvq34ndm1nk00000gn/T/serious_python_tempz9FFEv/__pypackages__/flet_runtime/app.py", line 385, in __connect_internal_sync
  File "/var/folders/2v/_cn0vsc92ss3fvq34ndm1nk00000gn/T/serious_python_tempz9FFEv/__pypackages__/flet_runtime/sync_local_socket_connection.py", line 72, in connect
  File "/var/folders/2v/_cn0vsc92ss3fvq34ndm1nk00000gn/T/serious_python_tempz9FFEv/__pypackages__/flet_runtime/sync_local_socket_connection.py", line 158, in __connection_loop
  File "/var/folders/2v/_cn0vsc92ss3fvq34ndm1nk00000gn/T/serious_python_tempz9FFEv/__pypackages__/flet_runtime/sync_local_socket_connection.py", line 82, in __on_message
TypeError: RegisterWebClientRequestPayload.__init__() missing 1 required positional argument: 'media'

I am new to git and coding. Please let me know if you require more info

**Comment by ndonkoHenri** [comment]
That traceback lives entirely inside `flet_runtime`'s local-socket transport, and that layer is gone on both sides: serious_python replaced the socket runner with the in-process [`dart_bridge`](https://github.com/flet-dev/dart-bridge) FFI bridge in 3.0.0, and Flet 0.86.x has no `flet_runtime` / `sync_local_socket_connection.py` at all — the `RegisterWebClientRequestPayload` that failed to construct doesn't exist either. The failure itself was a protocol mismatch between the Python `flet` inside your package and the Flutter Flet client it was talking to.

Closing as obsolete against 4.5.1+. If a built app fails to start on current Flet, please open a fresh issue at [flet-dev/flet](https://github.com/flet-dev/flet) with the `flet build` output.
