### ISSUE TITLE
Is there a step for having numpy in windows?

### ISSUE THREAD

**Issue by canavci312** [flet-dev/serious-python#96]
I'm trying to build on windows with python 3.11 and windows 11 but getting the following error after running script from the app. Is there an extra step to make it work that I'm missing? I couldnt find it in the documents

my requirements.txt
```
opencv-python==4.10.0.82
numpy==1.24.3
```

```
Install it via command:
    pip install numpy
Running Python program synchronously...Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\serious_python_tempdc757e66\__pypackages__\numpy\core\__init__.py", line 23, in <module>
  File "C:\Users\user\AppData\Local\Temp\serious_python_tempdc757e66\__pypackages__\numpy\core\multiarray.py", line 10, in <module>
  File "C:\Users\user\AppData\Local\Temp\serious_python_tempdc757e66\__pypackages__\numpy\core\overrides.py", line 6, in <module>
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

many reasons, often due to issues with your setup or how NumPy was
installed.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\serious_python_tempdc757e66\main.py", line 2, in <module>
  File "C:\Users\user\AppData\Local\Temp\serious_python_tempdc757e66\bot.py", line 1, in <module>
  File "C:\Users\user\AppData\Local\Temp\serious_python_tempdc757e66\__pypackages__\cv2\__init__.py", line 11, in <module>
  File "C:\Users\user\AppData\Local\Temp\serious_python_tempdc757e66\__pypackages__\numpy\__init__.py", line 141, in <module>
  File "C:\Users\user\AppData\Local\Temp\serious_python_tempdc757e66\__pypackages__\numpy\core\__init__.py", line 49, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "C:\Users\user\Documents\-\ui\-\build\windows\x64\runner\Debug\feribot.exe"
  * The NumPy version is: "1.24.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by FeodorFitsner** [comment]
Can you check if you have `.pyd` files inside `__pypackages__` of packaged app?

**Comment by canavci312** [comment]
> Can you check if you have `.pyd` files inside `__pypackages__` of packaged app?

I see a pyd file in cv2 folder. I dont see any in numpy folder or general __pypackages__

**Comment by remymenard** [comment]
Did you find a way to make it work on Windows? On macOS & Linux it works fine but on windows the numpy C library doesn't seem to load

**Comment by Verman98** [comment]
I am having the same issue as well. Even if I add the numpy library without any specification... 
Anyone has a solution?

**Comment by ndonkoHenri** [comment]
Sorry this sat unanswered for so long. The layout in that traceback — `__pypackages__` unpacked into `%TEMP%\serious_python_temp*` — is the packaging model we shipped up to 0.8.x, and it no longer exists. 0.9.0 moved site-packages out of the app zip and into the application bundle in an unpacked state, and 4.0.0 did the same for your app sources. On 4.5.1 a Windows build has `<exe-dir>\site-packages` (mirrored verbatim from the pip target dir by the plugin's CMake), native `.pyd`/`.dll` kept — desktop packaging cleanup never strips them — and `PYTHONHOME`/`PYTHONPATH` pointing at `<exe-dir>`, `site-packages`, `DLLs` and `Lib`.

@remymenard @Verman98 — your reports were against 0.8.x, which still used that same model, so they're covered by the same rewrite.

Closing as obsolete since there's nothing left to reproduce against. If `numpy` or `opencv` still fail to import in a Windows build on 4.5.1+, please open a fresh issue with the output of:

```bash
flet build windows -vv
```

plus a listing of the `site-packages\numpy` folder in the build output, and I'll dig into it.
